### PR TITLE
feat: superside careers page

### PR DESCRIPTION
**Pull request by yahorbarkouski**

### CODE REVIEW

**Comment by yahorbarkouski** [comment]
## Company Information 
| Company Name | Company Page | Company Page Status | Careers Page | Careers Page Status |
|----|------|-----|------|-----|
|Superside|https://www.superside.com/|Verified ✅|https://careers.superside.com/jobs|Verified ✅|


## Job Listings 
| Title | Job Listing | Status |
|-------|-------|-------|
|Senior Backend Engineer (Kotlin)|https://careers.superside.com/senior-backend-engineer-kotlin|Verified ✅|
|Creative Project Manager|https://careers.superside.com/creative-project-manager|Verified ✅|
|Creative (Presentation Design)|https://careers.superside.com/creatives-presentation-design|Verified ✅|
|Creative Lead (UX/UI)|https://careers.superside.com/uxui-creative-lead|Verified ✅|
|Creative Lead (Web)|https://careers.superside.com/creative-lead-web|Verified ✅|
|Creative Lead (Presentations Design)|https://careers.superside.com/creative-lead-presentations-design|Verified ✅|
|Creative (Generative AI)|https://careers.superside.com/creative-generative-ai|Verified ✅|
|Creative Strategist|https://careers.superside.com/creative-strategist|Verified ✅|

**Review by ybarkouski — APPROVED** [review]

**Comment by yahorbarkouski** [comment]
## Superside Job Listings Result

**Review by ybarkouski — APPROVED** [review]

**Comment by yahorbarkouski** [comment]
## Superside Job Listings Result

**Comment by yahorbarkouski** [comment]
## Company Information 
| Company Name | Company Page | Company Page Status | Careers Page | Careers Page Status |
|----|------|-----|------|-----|
|Superside|https://www.superside.com/|Verified ✅|https://careers.superside.com/jobs|Verified ✅|


## Job Listings 
| Title | Job Listing | Status |
|-------|-------|-------|
|Senior Backend Engineer (Kotlin)|https://careers.superside.com/senior-backend-engineer-kotlin|Verified ✅|
|Creative Project Manager|https://careers.superside.com/creative-project-manager|Verified ✅|
|Creative (Presentation Design)|https://careers.superside.com/creatives-presentation-design|Verified ✅|

**Review by ybarkouski — APPROVED** [review]

**Comment by yahorbarkouski** [comment]
## Superside Job Listings Result

**Review by plumpai — APPROVED** [review]

**Comment by plumpai** [comment]
## Superside Job Listings Result

**Review by plumpai — APPROVED** [review]

**Comment by plumpai** [comment]
## Superside Job Listings Result

**Review by plumpai — APPROVED** [review]

**Comment by plumpai** [comment]
## Superside Job Listings Result

**Review by plumpai — APPROVED** [review]

**Comment by plumpai** [comment]
## Superside Job Listings Result

**Pull request merged**
